### ISSUE TITLE
你的Consul中的key/value是什么

### ISSUE THREAD

**Issue by daconglee** [ww198643/Extensions.Configuration.Consul#1]
你的Consul中的key/value是什么，给个示例。
我运行你这个,TestConfig没值。

**Comment by ZeeLyn** [comment]
```csharp
services.Configure<Configs>(Configuration.GetSection("TestConfig"));
```
在服务注册里，注册了找TestConfig这个节点，拿Configs这个类下Name配置来举例，consul里对应的Key就应该是：TestConfig:Name    就跟我们平时用GetSection获取某个节点的配置一样的

你可以了解下配置框架的原理，推荐你看下蒋金楠的公众号（大内老A）里有专门介绍配置相关的文章，微软底层设计其实就是key/value

另外，因为种种原因这项目我很久没维护了，项目里有一个dev-ui分支，是做了一个专门用来管理配置的UI，基本能用 ，还有些bug，nuget也没上传，如果你感兴趣的话可以维护一下

**Comment by daconglee** [comment]
consul 中没有自动创建任何key/value项
我自己手工创建了，但是API中没有变化

key=TestClass

value= {"key":"1","name":"nnnn","title":"tttttttttt"}

**Comment by daconglee** [comment]
consul 中
key=TestClass
{"Key":"Config","Name":"nnnn","Title":"tttttttttt"}
都不行

**Comment by daconglee** [comment]
key=TestConfig:Name
value=myname

key=TestConfig:Key
value =key00000000000000

这样的就好了。

**Comment by ZeeLyn** [comment]
> key=TestConfig:Name
> value=myname
> 
> key=TestConfig:Key
> value =key00000000000000
> 
> 这样的就好了。

是的，我上面已经给你举了例子了
